### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by alvra** [thk1/send_wrapper#6]
If I'm not mistaken, calling `take`on the wrapper leaks the `thread_id` field since it calls `std::mem::forget()` [here](https://github.com/thk1/send_wrapper/blob/3886829ff9776df5154e53e6a27cb47378bb377c/src/lib.rs#L129).
The value should be moved out of the wrapper so it is managed separately and the rest can be dropped entirely.

What is the reason for storing the value as a pointer instead of keeping it as a box?
The latter avoids most unsafe code.

Also the panic messages should be swapped: https://github.com/thk1/send_wrapper/blob/3886829ff9776df5154e53e6a27cb47378bb377c/src/lib.rs#L92-L94.

**Comment by WaffleLapkin** [comment]
Note that `ThreadId` is `Copy`, so it can't implement drop and so "leaking" it is always fine.
